// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMhaq9b7w5Xw2pK6tKLcOFIBJ0z6T5lPI',
    appId: '1:247294125141:web:c2e565df731babf65ae0dc',
    messagingSenderId: '247294125141',
    projectId: 'alumni-npgc-flutter',
    authDomain: 'alumni-npgc-flutter.firebaseapp.com',
    storageBucket: 'alumni-npgc-flutter.appspot.com',
    measurementId: 'G-YTDRM34MZT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUPzyhVQkocnkTg8_cdxJiwdD6Xftg6r8',
    appId: '1:247294125141:android:8d93d87b1145284f5ae0dc',
    messagingSenderId: '247294125141',
    projectId: 'alumni-npgc-flutter',
    storageBucket: 'alumni-npgc-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwukHDpUNhv-s5hR_sGmZ-5K8ce5YdkvA',
    appId: '1:247294125141:ios:2c4bfca63b4753ff5ae0dc',
    messagingSenderId: '247294125141',
    projectId: 'alumni-npgc-flutter',
    storageBucket: 'alumni-npgc-flutter.appspot.com',
    iosClientId:
        '247294125141-rgj35cuc19e7hrbed2re92jhluk8l2gj.apps.googleusercontent.com',
    iosBundleId: 'com.alumninpgc.alumni',
  );
}
